# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 999491359402d8c114242b485967145d1df20e8f41af20dbfe2a3231ede8c752b414839c72c3104b8d159b84432f037f9d5f138ceae7c0265675cc9283e6f3fd

test:
  secret_key_base: b3e267e7d5b71d641b4c02b3a7051601fc470ec2dbe7cd19b68b39289afc01de09fb9889b48c6057c59e6c58edde2e906affe94b1f2f564bf5d6487fb4ef04a0

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
